config/routes.rb
Rails.application.routes.draw do
  resources :my_models

  resources :wicked, only: [:create, :show, :update]

  resources :wicked_using_get, only: [:new, :create, :show, :update]

  root 'my_models#index'

end

app/models/my_model.rb
class MyModel < ActiveRecord::Base
  attr_accessor :form_step

  cattr_accessor :form_steps do
    %w(profile social_profile address vehicle verify)
  end

  with_options :if => -> { required_for_step?(:profile) } do |step|
    step.validates :first_name, :presence => true
    step.validates :middle_name, :presence => true
    step.validates :last_name, :presence => true
    # step.validates :suffix, :presence => true
  end

  with_options :if => -> { required_for_step?(:social_profile) } do |step|
    step.validates :twitter_username, :presence => true
    step.validates :github_username, :presence => true
    step.validates :website, :presence => true
  end

  with_options :if => -> { required_for_step?(:address) } do |step|
    step.validates :city, :presence => true
    step.validates :state, :presence => true
    step.validates :zipcode, :presence => true, :numericality => true
    step.validates :street, :presence => true
  end

  with_options :if => -> { required_for_step?(:vehicle) } do |step|
    step.validates :car_year, :presence => true, :numericality => true
    step.validates :car_maker, :presence => true
    step.validates :car_model, :presence => true
    step.validates :car_type, :presence => true
  end

  private
    def required_for_step?(step)
      # All fields are required if no form step is present
      return true if form_step.nil?

      # All fields from previous steps are required if the
      # step parameter appears before or we are on the current step
      self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_models_controller.rb
class MyModelsController < ApplicationController
  before_action :set_my_model, only: [:show, :edit, :update, :destroy]

  # GET /my_models
  # GET /my_models.json
  def index
    @my_models = MyModel.all
  end

  # GET /my_models/1
  # GET /my_models/1.json
  def show
  end

  # GET /my_models/new
  def new
    @my_model = MyModel.new
  end

  # GET /my_models/1/edit
  def edit
  end

  # POST /my_models
  # POST /my_models.json
  def create
    @my_model = MyModel.new(my_model_params)

    respond_to do |format|
      if @my_model.save
        format.html { redirect_to @my_model, notice: 'My model was successfully created.' }
        format.json { render :show, status: :created, location: @my_model }
      else
        format.html { render :new }
        format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_models/1
  # PATCH/PUT /my_models/1.json
  def update
    respond_to do |format|
      if @my_model.update(my_model_params)
        format.html { redirect_to @my_model, notice: 'My model was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_model }
      else
        format.html { render :edit }
        format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_models/1
  # DELETE /my_models/1.json
  def destroy
    @my_model.destroy
    respond_to do |format|
      format.html { redirect_to my_models_url, notice: 'My model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_model
      @my_model = MyModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_model_params
      params.require(:my_model).permit(:first_name, :middle_name, :last_name, :suffix, :twitter_username, :github_username, :website, :city, :state, :zipcode, :street, :car_year, :car_maker, :car_model, :car_type)
    end
end

app/controllers/wicked_controller.rb
class WickedController < ApplicationController
  include Wicked::Wizard
  steps *MyModel.form_steps

  def create
    @my_model = MyModel.new
    @my_model.save(validate: false)
    redirect_to wicked_path(steps.first, :my_model_id => @my_model.id)
  end

  def show
    @my_model = MyModel.find(params[:my_model_id])
    render_wizard
  end

  def update
    @my_model = MyModel.find(filter_params[:id])
    if @my_model.update(filter_params(step))
      redirect_to wicked_path(@next_step, :my_model_id => filter_params[:id])
    else
      render_wizard @my_model
    end
  end

  private
    def filter_params(step=nil)
      permitted_attributes = [:id, :first_name, :middle_name, :last_name, :suffix, :twitter_username, :github_username, :website, :city, :state, :zipcode, :street, :car_year, :car_maker, :car_model, :car_type]
      params.require(:my_model).permit(permitted_attributes).merge(form_step: step)
    end
end

app/controllers/wicked_using_get_controller.rb
class WickedUsingGetController < ApplicationController
  include Wicked::Wizard
  steps *MyModel.form_steps

  def new
    redirect_to wicked_using_get_path(steps.first)
  end

  def create
    @my_model = MyModel.new(filter_params(step))

    if @my_model.save
      redirect_to @my_model, notice: 'My model was successfully created.'
    else
      render_wizard @my_model
    end
  end

  def show
    @my_model = MyModel.new(basic_params(step))
    render_wizard
  end

  def update
    @my_model = MyModel.new(filter_params(step))
    if @my_model.valid?
      redirect_to wicked_using_get_path(@next_step, filter_params(step))
    else
      render_wizard @my_model
    end
  end

  private
    def basic_params(step=nil)
      permitted_attributes = [:first_name, :middle_name, :last_name, :suffix, :twitter_username, :github_username, :website, :city, :state, :zipcode, :street, :car_year, :car_maker, :car_model, :car_type]
      params.permit(permitted_attributes).merge(form_step: step)
    end

    def filter_params(step=nil)
      permitted_attributes = [:first_name, :middle_name, :last_name, :suffix, :twitter_username, :github_username, :website, :city, :state, :zipcode, :street, :car_year, :car_maker, :car_model, :car_type]
      params.require(:my_model).permit(permitted_attributes).merge(form_step: step)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_models_helper.rb
module MyModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWickedExamples</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_models/edit.html.erb
<h1>Editing my_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_model %> |
<%= link_to 'Back', my_models_path %>

app/views/my_models/index.html.erb
<h1>Listing my_models</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Suffix</th>
      <th>Twitter username</th>
      <th>Github username</th>
      <th>Website</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Street</th>
      <th>Car year</th>
      <th>Car maker</th>
      <th>Car model</th>
      <th>Car type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_models.each do |my_model| %>
      <tr>
        <td><%= my_model.first_name %></td>
        <td><%= my_model.middle_name %></td>
        <td><%= my_model.last_name %></td>
        <td><%= my_model.suffix %></td>
        <td><%= my_model.twitter_username %></td>
        <td><%= my_model.github_username %></td>
        <td><%= my_model.website %></td>
        <td><%= my_model.city %></td>
        <td><%= my_model.state %></td>
        <td><%= my_model.zipcode %></td>
        <td><%= my_model.street %></td>
        <td><%= my_model.car_year %></td>
        <td><%= my_model.car_maker %></td>
        <td><%= my_model.car_model %></td>
        <td><%= my_model.car_type %></td>
        <td><%= link_to 'Show', my_model %></td>
        <td><%= link_to 'Edit', edit_my_model_path(my_model) %></td>
        <td><%= link_to 'Destroy', my_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New MyModel via Basic Form', new_my_model_path %><br />
<%= link_to 'New MyModel via Wicked Wizard', wicked_index_path, method: :post %><br />
<%= link_to 'New MyModel via Wicked Wizard passing params via GET and storing model only once', new_wicked_using_get_path %>

app/views/my_models/new.html.erb
<h1>New my_model</h1>

<%= render 'form' %>

<%= link_to 'Back', my_models_path %>

app/views/my_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @my_model.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @my_model.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @my_model.last_name %>
</p>

<p>
  <strong>Suffix:</strong>
  <%= @my_model.suffix %>
</p>

<p>
  <strong>Twitter username:</strong>
  <%= @my_model.twitter_username %>
</p>

<p>
  <strong>Github username:</strong>
  <%= @my_model.github_username %>
</p>

<p>
  <strong>Website:</strong>
  <%= @my_model.website %>
</p>

<p>
  <strong>City:</strong>
  <%= @my_model.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @my_model.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @my_model.zipcode %>
</p>

<p>
  <strong>Street:</strong>
  <%= @my_model.street %>
</p>

<p>
  <strong>Car year:</strong>
  <%= @my_model.car_year %>
</p>

<p>
  <strong>Car maker:</strong>
  <%= @my_model.car_maker %>
</p>

<p>
  <strong>Car model:</strong>
  <%= @my_model.car_model %>
</p>

<p>
  <strong>Car type:</strong>
  <%= @my_model.car_type %>
</p>

<%= link_to 'Edit', edit_my_model_path(@my_model) %> |
<%= link_to 'Back', my_models_path %>

app/views/wicked/address.html.erb
address

<%= form_for @my_model, url: wicked_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id %>

    <fieldset>

      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city %>
      </div>

      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state %>
      </div>

      <div class="field">
        <%= f.label :zipcode %><br>
        <%= f.number_field :zipcode %>
      </div>

      <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:my_model_id => @my_model.id}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked/profile.html.erb
profile

<%= form_for @my_model, url: wicked_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id %>

    <fieldset>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :middle_name %><br>
        <%= f.text_field :middle_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :suffix %><br>
        <%= f.text_field :suffix %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked/social_profile.html.erb
social profile

<%= form_for @my_model, url: wicked_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id %>

    <fieldset>

      <div class="field">
        <%= f.label :twitter_username %><br>
        <%= f.text_field :twitter_username %>
      </div>

      <div class="field">
        <%= f.label :github_username %><br>
        <%= f.text_field :github_username %>
      </div>

      <div class="field">
        <%= f.label :website %><br>
        <%= f.text_field :website %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:my_model_id => @my_model.id}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked/vehicle.html.erb
vehicle

<%= form_for @my_model, url: wicked_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id %>

    <fieldset>

      <div class="field">
        <%= f.label :car_year %><br>
        <%= f.number_field :car_year %>
      </div>

      <div class="field">
        <%= f.label :car_maker %><br>
        <%= f.text_field :car_maker %>
      </div>

      <div class="field">
        <%= f.label :car_model %><br>
        <%= f.text_field :car_model %>
      </div>

      <div class="field">
        <%= f.label :car_type %><br>
        <%= f.text_field :car_type %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:my_model_id => @my_model.id}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked/verify.html.erb
verify

<%= form_for @my_model, url: wicked_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id %>

    <fieldset>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :middle_name %><br>
        <%= f.text_field :middle_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :suffix %><br>
        <%= f.text_field :suffix, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :twitter_username %><br>
        <%= f.text_field :twitter_username, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :github_username %><br>
        <%= f.text_field :github_username, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :website %><br>
        <%= f.text_field :website, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :zipcode %><br>
        <%= f.number_field :zipcode, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_year %><br>
        <%= f.number_field :car_year, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_maker %><br>
        <%= f.text_field :car_maker, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_model %><br>
        <%= f.text_field :car_model, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_type %><br>
        <%= f.text_field :car_type, { readonly: 'true' } %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:my_model_id => @my_model.id}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked_using_get/_tmp_storage_fields.html.erb
<!--Tag-along Model Parameters-->
<%= f.hidden_field :first_name %>
<%= f.hidden_field :middle_name %>
<%= f.hidden_field :last_name %>
<%= f.hidden_field :suffix %>

<%= f.hidden_field :twitter_username %>
<%= f.hidden_field :github_username %>
<%= f.hidden_field :website %>

<%= f.hidden_field :city %>
<%= f.hidden_field :state %>
<%= f.hidden_field :zipcode %>
<%= f.hidden_field :street %>

<%= f.hidden_field :car_year %>
<%= f.hidden_field :car_maker %>
<%= f.hidden_field :car_model %>
<%= f.hidden_field :car_type %>

app/views/wicked_using_get/address.html.erb
address

<%= form_for @my_model, url: wicked_using_get_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render 'tmp_storage_fields', f: f %>

    <fieldset>

      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city %>
      </div>

      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state %>
      </div>

      <div class="field">
        <%= f.label :zipcode %><br>
        <%= f.number_field :zipcode %>
      </div>

      <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:params => params}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked_using_get/profile.html.erb
profile

<%= form_for @my_model, url: wicked_using_get_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render 'tmp_storage_fields', f: f %>

    <fieldset>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :middle_name %><br>
        <%= f.text_field :middle_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :suffix %><br>
        <%= f.text_field :suffix %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked_using_get/social_profile.html.erb
social profile

<%= form_for @my_model, url: wicked_using_get_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render 'tmp_storage_fields', f: f %>

    <fieldset>

      <div class="field">
        <%= f.label :twitter_username %><br>
        <%= f.text_field :twitter_username %>
      </div>

      <div class="field">
        <%= f.label :github_username %><br>
        <%= f.text_field :github_username %>
      </div>

      <div class="field">
        <%= f.label :website %><br>
        <%= f.text_field :website %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:params => params}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked_using_get/vehicle.html.erb
vehicle

<%= form_for @my_model, url: wicked_using_get_path, html: { method: :put, class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render 'tmp_storage_fields', f: f %>

    <fieldset>

      <div class="field">
        <%= f.label :car_year %><br>
        <%= f.number_field :car_year %>
      </div>

      <div class="field">
        <%= f.label :car_maker %><br>
        <%= f.text_field :car_maker %>
      </div>

      <div class="field">
        <%= f.label :car_model %><br>
        <%= f.text_field :car_model %>
      </div>

      <div class="field">
        <%= f.label :car_type %><br>
        <%= f.text_field :car_type %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:params => params}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>

app/views/wicked_using_get/verify.html.erb
verify

<%= form_for @my_model, url: wicked_using_get_index_path, html: { class: 'form' } do |f| %>
    <% if @my_model.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

          <ul>
            <% @my_model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render 'tmp_storage_fields', f: f %>

    <fieldset>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :middle_name %><br>
        <%= f.text_field :middle_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :suffix %><br>
        <%= f.text_field :suffix, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :twitter_username %><br>
        <%= f.text_field :twitter_username, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :github_username %><br>
        <%= f.text_field :github_username, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :website %><br>
        <%= f.text_field :website, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :zipcode %><br>
        <%= f.number_field :zipcode, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_year %><br>
        <%= f.number_field :car_year, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_maker %><br>
        <%= f.text_field :car_maker, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_model %><br>
        <%= f.text_field :car_model, { readonly: 'true' } %>
      </div>

      <div class="field">
        <%= f.label :car_type %><br>
        <%= f.text_field :car_type, { readonly: 'true' } %>
      </div>

    </fieldset>

    <div class="actions">
      <%= link_to 'Back', previous_wizard_path({:params => params}), :class => 'btn btn-default' %>
      <%= link_to 'Cancel', my_models_path, data: { confirm: 'Are you sure you want to cancel the wizard?' } %>
      <%= f.submit %>
    </div>
<% end %>